### ISSUE TITLE
Generic instances for type constructors wrong?

### ISSUE THREAD

**Issue by eskimor** [eskimor/purescript-bridge#11]
As @akegalj pointed out:

https://github.com/eskimor/purescript-bridge/blob/master/src/Language/PureScript/Bridge/Printer.hs#L77

The derive Generic instance only covers the typename, but it should also include type parameters:

```purescript
data Foo a = Foo Int

derive instance genericFoo :: Generic (Foo a) 
```

instead of just

```purescript
derive instance genericFoo :: Generic Foo
```

**Comment by eskimor** [comment]
Thanks for pointing this out!

**Comment by akegalj** [comment]
> I should use the Preview functionality before sending - I guess you just got an awful huge amount of notifications. Sorry about that!

np :)

> They are not needed for Phantom types

I didn't think about this use case until I read this comment. It is implemented in this PR and it should work (at least for some simple cases that I have tried).
