### ISSUE TITLE
Change warning message

### ISSUE THREAD

**Issue by akegalj** [eskimor/purescript-bridge#14]
```
Make sure you have the following PureScript packages installed:

  - purescript-prim
```
This sounds more like an error. It should be a warning. I run into few people getting confused thinking this is an error message. What do you think of adding prefix `WARNING: `?

suggestion by @domenkozar is:
> `Sucessfully created` should come the latest; and the message should mention `Using generated purescript packages ...`

**Comment by eskimor** [comment]
ok! Thanks for the feedback!

**Comment by eskimor** [comment]
Closing - Please try 0.8.0.1 - I hope it is better now, if not - re-open!
