### ISSUE TITLE
Upgrading to purescript 0.10

### ISSUE THREAD

**Issue by boothead** [eskimor/purescript-bridge#16]
What's the reason that we can't use ps 0.10? Anything I can help with?

**Comment by sectore** [comment]
@boothead Due an an issue of updating `purescript-argonaut-generic-codecs` to `0.10.2` https://github.com/eskimor/purescript-argonaut-generic-codecs/pull/8 

The reason for that is a dependency of `purescript-strongcheck-generics`, which can't be updated to `0.10.x`  https://github.com/zudov/purescript-strongcheck-generics/issues/5 

Any help on this - especially fixing issue off `purescript-strongcheck-generics` - would be very appreciated

**Comment by boothead** [comment]
Wow - that looks like a tricky one!

**Comment by legrostdg** [comment]
With #21 merged, we should be able to use ps 0.10, so I think this issue can be closed.

**Comment by eskimor** [comment]
Thank you!

**Comment by boothead** [comment]
Great! So the generics bug isn't a show stopper?

**Comment by sectore** [comment]
@boothead The generic bug is already there, but author of `purescript-strongcheck-generics` has updated the library to `[v0.5.1](https://github.com/zudov/purescript-strongcheck-generics/releases/tag/v0.5.1 with a pragmatic )` with a pragmatic solution as mentioned here https://github.com/zudov/purescript-strongcheck-generics/issues/5#issuecomment-276624405.
