### ISSUE TITLE
Deprecated types for Lenses and Prisms

### ISSUE THREAD

**Issue by sectore** [eskimor/purescript-bridge#19]
@boothead First of all thank you for supporting Lenses / Prisms!

The generated code is using types such as `LensP` and `PrismP`, which are deprecated with [`purescript-profunctor-lenses v2.0.0`](https://github.com/purescript-contrib/purescript-profunctor-lenses/releases/tag/v2.0.0).

What is the version of `purescript-profunctor-lenses` you are working with?

**Comment by boothead** [comment]
The problem as I understand it is that the purescript bridge generated code is constrained to an older version of purescript due to the generic issue that you commented on here https://github.com/eskimor/purescript-bridge/issues/16.

I hope to be able to have a look at this bug soonish 😀
