### ISSUE TITLE
Can't derive `Generic` for types containing `Map`

### ISSUE THREAD

**Issue by fosskers** [eskimor/purescript-bridge#39]
Related to #38 

If one of my bridged types contains a `Map`, say:

```haskell
data Blog = Blog { title :: Text, freqs :: M.Map Text Int } deriving (Generic, ToJSON)
```
It needs `Generic` here in order to be bridgable. Likewise, `purescript-bridge` tries to generate one the PS side...
```purescript
derive instance genericBlog :: Generic Blog
```
but!
```
[1/1 NoInstanceFound] src/Types.purs:22:8

  22  derive instance genericBlog :: Generic Blog
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  No type class instance was found for
  
    Data.Generic.Generic (Map String Int)
  
  while applying a function toSpine
    of type Generic t0 => t0 -> GenericSpine
    to argument $1.freqs
  while checking that expression toSpine ($1.freqs)
    has type GenericSpine
  in value declaration genericBlog
  
  where t0 is an unknown type
```
even though this is advertised as being possible in the [purescript-maps](https://github.com/purescript/purescript-maps/issues/51#issuecomment-272498192) library.

Thoughts? Please and thanks.

**Comment by eskimor** [comment]
Map does not provide a Generic instance you have to use a newtype wrapper where you can derive one. So you should configure purescript-bridge to bridge a Haskell map to something like:
```purescript
newtype SerializeableMap k v = SerializeableMap (Map k v)

derive instance genericSerializableMap :: Generic SerializeableMap
```

This should work.

**Comment by eskimor** [comment]
Closing as this is not really an issue with purescript-bridge.

**Comment by fosskers** [comment]
Unfortunately I can't get this to work. Following your advice, I have:
```haskell
{-# LANGUAGE DataKinds, TypeOperators #-}
{-# LANGUAGE DeriveGeneric, DeriveAnyClass #-}

module Common where

import           Data.Aeson (ToJSON)
import qualified Data.Map.Strict as M
import           Protolude
import           Servant.API

---

type API = "posts" :> Get '[JSON] [Blog]

newtype GMap k v = GMap { gmap :: M.Map k v } deriving (Generic, ToJSON)

data Blog = Blog { title :: Text, freqs :: GMap Text Int } deriving (Generic, ToJSON)
```
which becomes the following Purescript:
```purescript
-- ... imports and things

newtype Blog =
    Blog {
      title :: String
    , freqs :: GMap String Int
    }

derive instance genericBlog :: Generic Blog

derive instance newtypeBlog :: Newtype Blog _

-- ... lenses and things

newtype GMap k v =
    GMap {
      gmap :: Map k v
    }

derive instance genericGMap :: (Generic k, Generic v) => Generic (GMap k v)

derive instance newtypeGMap :: Newtype (GMap k v) _
```
but we get the same error at compile time:
```
  No type class instance was found for
  
    Data.Generic.Generic (Map k1 v2)
```

**Comment by eskimor** [comment]
Oh sorry. That's not what I meant. You don't define the newtype on the Haskell side, you define one on the PureScript side and then you use a bridge for translating Haskell Map to this newtype `GMap`. You basically make Map a primitive type that purescript bridge just uses for composing types that have Maps in them. I hope that makes sense.

This way purescript-bridge won't "touch" the newtype (won't try to derive a Generic instance) but just uses it. Adds the relevant import as specified in the psType and be done with it.

**Comment by fosskers** [comment]
Hm, neither of these seems to compile in PS still:
```purescript
newtype GMap = GMap (Map String Int)
derive instance genericGMap :: Generic GMap
```
nor
```purescript
newtype GMap k v = GMap (Map k v)
derive instance genericGMap :: (Generic k, Generic v) => Generic (GMap k v)
```
Either way we're still told something along the lines of:
```
  19  derive instance genericGMap :: (Generic k, Generic v) => Generic (GMap k v)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  No type class instance was found for
  
    Data.Generic.Generic (Map k1 v2)
```

**Comment by fosskers** [comment]
Err, wait. Do I still still the `Generic` instance? The whole point of this was to try and auto-generate types and API calls to my servant backend, such that all the JSON conversion would "just work".

**Comment by eskimor** [comment]
Sorry I misread the issue you [referenced](https://github.com/purescript/purescript-maps/issues/51#issuecomment-272498192). According to the issue it should work if the Map is part of a record (which needs a newtype). If this seems unnecessary complex or does not work either, you could simply transmit the Map over the wire as association list [(key,val)] , which is probably the path I would take.

**Comment by fosskers** [comment]
Good point - the Map to be wired isn't needed on the backend for its Map-ness, and since it'll only be called for once on the front-end, I can construct it myself from assoc-list as you suggest.

**Comment by fosskers** [comment]
Yup, that did it! Thanks for your help.
