### ISSUE TITLE
Missing hackage documentation

### ISSUE THREAD

**Issue by bsermons** [eskimor/purescript-bridge#4]
The links in the README to the documentation on hackage both return a 404 response for the latest versions.  Not a big deal since I can just read the src comments but thought I'd let you know.

Thanks for making this and servant-purescript btw.  They are something I wanted to do but didn't know enough haskell type-fu to make it happn :smile:

**Comment by eskimor** [comment]
hackage has not yet built the docs for the latest versions, that's pretty common unfortunately. Although this time it takes even longer than usual. Thanks for reporting though!

If you have any questions feel free to ask - you can write me an email or file an issue, whatever is more appropriate. Glad if it is useful for you! :-)

**Comment by eskimor** [comment]
Do servant-purescript and purescript-bridge work for you? Did you have any problems? If so, please file issues - thank you!

**Comment by bsermons** [comment]
Oh, ok that makes sense. I've never published to hackage so didn't know how it works.  I haven't had a chance to test them yet but hopefully today and tomorrow I can get something set up.

I'll let you know if I have any issues. Thanks

**Comment by epsilonhalbe** [comment]
there is quite an easy way to upload the docs by hand - http://fuuzetsu.co.uk/blog/posts/2014-01-06-Fix-your-Hackage-documentation.html then we can make sure that everyone has access to them. moreover using the latest (HEAD) of haddock one gets nice features like mathjax in documentation and if I recall correctly highlighting and links in the source code.

**Comment by eskimor** [comment]
fixed. Thanks @epsilonhalbe
