### ISSUE TITLE
[Request] Generate Eq/Ord/Show instances if available

### ISSUE THREAD

**Issue by fosskers** [eskimor/purescript-bridge#40]
If `Eq`, `Ord` and/or `Show` are present on the original type to be bridged, can those instances be created on the Purescript side too? I often find myself wanting these instances on both sides.

**Comment by werbitt** [comment]
@fosskers Thanks for this. Is there a reason that in your original issue you mentioned `Show` instances, but decided not to add them?

I could use `Show` on my bridged types, but I wasn't sure if there's a different solution I'm not aware of.

Thanks.

**Comment by fosskers** [comment]
Oh geez, I've totally forgotten by now. It looks like original contribution was made exactly a year ago. 

I *think* I ended up not needing `Show` on the other end, for whatever reason. Or there was some conflict due to newtypes. Forgive me, I'm scratching at the back of my memory for this.

**Comment by werbitt** [comment]
OK cool, no problem, just checking that there wasn't something obvious I wasn't aware of since I'm still feeling my way around purescript.

**Comment by fosskers** [comment]
I was much the same :) Good luck.
