### ISSUE TITLE
Point to shmish111's more maintained fork?

### ISSUE THREAD

**Issue by marcusbuffett** [eskimor/purescript-bridge#48]
Recently discovered this project and couldn't get it working, but it seems like https://github.com/shmish111/purescript-bridge has been updated. Should this project point there as it's more maintained?

**Comment by eskimor** [comment]
Not sure, it is not that I don't maintain this project. I still review and merge PRs and make releases, where appropriate. Having said that, I am not necessarily opposed to handing control over to someone actually still using the library.

**Comment by marcusbuffett** [comment]
Ah got it, sorry about that. I just discovered the other one after  this one didn't work (I think because of the generic import it uses). Gonna close this.
