### ISSUE TITLE
nested types

### ISSUE THREAD

**Issue by peterbecich** [eskimor/purescript-bridge#58]
I think nested types may be broken, i.e. `Baz` in `Foo`:

https://github.com/eskimor/purescript-bridge/blob/8dce36333c91b461bd1869ac7ddb0ea8102f9fa5/example/src/Types.hs#L19-L39

This branch https://github.com/peterbecich/purescript-bridge/tree/nested-example fixes the issue. It needs some more work.

The example Haskell value
https://github.com/eskimor/purescript-bridge/blob/e5e380ec5d8786d69a9ad064ca0957307cac397f/example/src/MyLib.hs#L30-L36
successfully round-trips.

**Comment by peterbecich** [comment]
I think nested types are fixed: https://github.com/eskimor/purescript-bridge/pull/57#issuecomment-860154977

**Comment by peterbecich** [comment]
Also implemented here I think: https://github.com/input-output-hk/purescript-bridge/pull/3 and https://github.com/input-output-hk/purescript-bridge/pull/4

**Comment by eskimor** [comment]
Thanks!

**Comment by peterbecich** [comment]
https://github.com/eskimor/purescript-bridge/pull/57
