### ISSUE TITLE
Lens support

### ISSUE THREAD

**Issue by eskimor** [eskimor/purescript-bridge#6]
If backend uses _ in fieldnames - auto generate lenses in PS! This would be awesome!

**Comment by epsilonhalbe** [comment]
I'll have a look at this

**Comment by boothead** [comment]
I've got a need for this too. @eskimor @epsilonhalbe Do you mind if I have a crack at it?

**Comment by eskimor** [comment]
I would gladly merge a PR for that ;-)

**Comment by boothead** [comment]
Working on it in #15 :-)

**Comment by eskimor** [comment]
Thanks @boothead!
