### ISSUE TITLE
Data.Word i.e. GHC.Word is not supported

### ISSUE THREAD

**Issue by marijanp** [eskimor/purescript-bridge#68]
When generating the purescript module for  a type using `Data.Word` e.g.
```
import Data.Word (Word64)
data Foo = Foo {
  _bar :: Word64
}
```
The converted code results in 
```
import GHC.Word
...
....
```
Expected code is:
```
import Data.UInt64
...
```

**Comment by eskimor** [comment]
Should be easy to fix, by adding a corresponding `BridgePart` [here](https://github.com/eskimor/purescript-bridge/blob/master/src/Language/PureScript/Bridge/Primitives.hs) and adding it to the [`defaultBridge`](https://github.com/eskimor/purescript-bridge/blob/master/src/Language/PureScript/Bridge.hs#L128).

**Comment by marijanp** [comment]
@eskimor Do you have any opinions on what the respective PS type should be for `Data.Word`?

**Comment by eskimor** [comment]
Not really, except that bringing in a package might not be good for such a simple type. The suggested Data.UInt64 should be a safe bet, in case there is nothing more appropriate.

**Comment by marijanp** [comment]
@eskimor I would like to stick with [purescript-word](https://pursuit.purescript.org/packages/purescript-word/0.4.1/docs/Data.Word) it has tests and looks solid to me. I also talked to other purescript users, they agree and noted that an alternative would be to just use `Number`. But I'ld like to have the type safety.

**Comment by eskimor** [comment]
Yes - I actually started already, but got distracted by other things.
