### ISSUE TITLE
listBridge shadows stringBridge

### ISSUE THREAD

**Issue by diego9627** [eskimor/purescript-bridge#7]
When using defaultBridge, listBridge shadows stringBridge and Strings are converted to Array Char.

**Comment by eskimor** [comment]
WTF? Really? This never happend to me, ok - I'll investigate, I'll keep you posted!

**Comment by eskimor** [comment]
Yeah! Of course and it is also clear why this never happened to me too - I never use String :-P Expect a fix by tomorrow! Thanks for your report!
