### ISSUE TITLE
Request for new Hackage release

### ISSUE THREAD

**Issue by peterbecich** [eskimor/purescript-bridge#70]
Can we make a new tag and release it to Hackage?
https://hackage.haskell.org/package/purescript-bridge

I can do if if you transfer ownership of the Hackage package to me; my username is "peterbecich".

Thank you

**Comment by eskimor** [comment]
You should be maintainer now. Thank you!

**Comment by peterbecich** [comment]
great, thanks, done: https://hackage.haskell.org/package/purescript-bridge
